const MAKE_TO_FILE: Record<string, string> = {
  abarth: "abarth",
  "alfa romeo": "alfa-romeo",
  "alfa-romeo": "alfa-romeo",
  alfaromeo: "alfa-romeo",
  "aston martin": "aston-martin",
  "aston-martin": "aston-martin",
  astonmartin: "aston-martin",
  audi: "audi",
  bentley: "bentley",
  bmw: "bmw",
  byd: "byd",
  chevrolet: "chevrolet",
  chrysler: "chrysler",
  citroen: "citroen",
  cupra: "cupra",
  dacia: "dacia",
  daihatsu: "daihatsu",
  dodge: "dodge",
  ds: "ds",
  "ds automobiles": "ds",
  ferrari: "ferrari",
  fiat: "fiat",
  ford: "ford",
  genesis: "genesis",
  honda: "honda",
  hyundai: "hyundai",
  infiniti: "infiniti",
  isuzu: "isuzu",
  jaguar: "jaguar",
  jeep: "jeep",
  kia: "kia",
  lamborghini: "lamborghini",
  "land rover": "land-rover",
  "land-rover": "land-rover",
  landrover: "land-rover",
  lexus: "lexus",
  lotus: "lotus",
  maserati: "maserati",
  mazda: "mazda",
  "mercedes-benz": "mercedes-benz",
  mercedes: "mercedes-benz",
  mg: "mg",
  mini: "mini",
  mitsubishi: "mitsubishi",
  nissan: "nissan",
  peugeot: "peugeot",
  polestar: "polestar",
  porsche: "porsche",
  renault: "renault",
  "rolls royce": "rolls-royce",
  "rolls-royce": "rolls-royce",
  rollsroyce: "rolls-royce",
  saab: "saab",
  seat: "seat",
  skoda: "skoda",
  smart: "smart",
  ssangyong: "ssangyong",
  subaru: "subaru",
  suzuki: "suzuki",
  tesla: "tesla",
  toyota: "toyota",
  vauxhall: "vauxhall",
  volkswagen: "volkswagen",
  vw: "volkswagen",
  volvo: "volvo",
};

export function getMakeLogoPath(make?: string): string | null {
  if (!make) return null;
  const key = make.toLowerCase().trim();
  const file = MAKE_TO_FILE[key];
  return file ? `/logos/${file}.png` : null;
}
