import type { ReactNode } from "react";
import Image from "next/image";
import MobileSearchCue from "./MobileSearchCue";

interface LandingHeroProps {
  h1: string;
  subtitle: string;
  bullets: string[];
  exampleCard: ReactNode;
  backLinkHref?: string;
  backLinkText?: string;
  badgeText?: string;
  /** Filename in /public/previews/*.png. Shown as a small tilted thumbnail
   *  on mobile (right of the H1) and a large preview on desktop (right
   *  column). Generated by scripts/generate-previews.ts. */
  previewImage?: string;
}

/**
 * Shared landing-page hero used by /car-check, /tax-check, /mileage-check,
 * /ulez-check, /recall-check. Two distinct layouts:
 *  - Mobile: split row [badges + h1] + [thumb], then full-width subtitle/bullets
 *  - Desktop: single grid [badges + h1 + subtitle + bullets] | [large screenshot]
 *
 * /mot-check, /car-valuation, /running-costs use hand-written heroes with the
 * same shape — kept inline there for now.
 */
export default function LandingHero({
  h1,
  subtitle,
  bullets,
  exampleCard,
  backLinkHref = "/tools",
  backLinkText = "← Back to all tools",
  badgeText = "Free · No signup · Official UK data",
  previewImage,
}: LandingHeroProps) {
  return (
    <div className="relative overflow-hidden border-b border-slate-800 bg-gradient-to-b from-slate-900 via-slate-950 to-slate-950">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_rgba(16,185,129,0.12),_transparent_60%)]" />
      <div className="relative max-w-5xl mx-auto px-4 pt-8 pb-6 lg:pb-10">
        <a
          href={backLinkHref}
          className="text-blue-400 hover:text-blue-300 text-sm mb-6 inline-block"
        >
          {backLinkText}
        </a>

        {/* ─── MOBILE LAYOUT (<lg) ─── */}
        <div className="lg:hidden">
          <div
            className={`grid gap-3 items-start ${
              previewImage ? "grid-cols-[1fr_125px] sm:grid-cols-[1fr_150px]" : ""
            }`}
          >
            <h1 className="min-w-0 text-2xl sm:text-3xl font-bold text-slate-100 leading-tight">
              {h1}
            </h1>
            {previewImage && (
              <div className="flex justify-end">
                <div className="relative">
                  <Image
                    src={`/previews/${previewImage}`}
                    alt=""
                    width={125}
                    height={165}
                    className="rounded-lg border border-slate-700/60 shadow-xl shadow-cyan-500/15 -rotate-2 object-cover object-top"
                    style={{ width: 125, height: 165 }}
                  />
                  <span className="absolute -top-2 -right-2 px-1.5 py-0.5 rounded-full bg-amber-400 text-slate-900 text-[9px] font-bold uppercase tracking-wider shadow-lg rotate-3">
                    Sample
                  </span>
                </div>
              </div>
            )}
          </div>
          <MotReminderPill className="mt-4" />
          <p className="mt-4 text-base text-slate-300 leading-relaxed">
            {subtitle}
          </p>
          <HeroBulletList bullets={bullets} className="mt-4 space-y-1.5" />
        </div>

        {/* ─── DESKTOP LAYOUT (≥lg) ─── */}
        <div className="hidden lg:grid lg:grid-cols-[1.1fr_0.9fr] lg:gap-8 lg:items-center">
          <div>
            <h1 className="text-5xl font-bold text-slate-100 leading-tight">
              {h1}
            </h1>
            <MotReminderPill className="mt-4" />
            <p className="mt-4 text-lg text-slate-300 leading-relaxed max-w-xl">
              {subtitle}
            </p>
            <HeroBulletList bullets={bullets} className="mt-5 space-y-2" />
          </div>

          {previewImage ? (
            <div className="relative mx-auto lg:mx-0">
              <Image
                src={`/previews/${previewImage}`}
                alt="Sample result"
                width={320}
                height={420}
                className="rounded-2xl border border-slate-700/60 shadow-2xl shadow-cyan-500/10 object-cover object-top"
                style={{ width: 320, height: 420 }}
              />
              <span className="absolute -top-3 -right-3 px-2.5 py-1 rounded-full bg-amber-400 text-slate-900 text-[10px] font-bold uppercase tracking-wider shadow-lg rotate-3">
                Sample
              </span>
            </div>
          ) : (
            <div className="card-zoom-wrapper mx-auto lg:mx-0">{exampleCard}</div>
          )}
        </div>

        {/* Mobile-only A/B/C affordance pointing to the search input below */}
        <MobileSearchCue />
      </div>
    </div>
  );
}

function MotReminderPill({ className = "" }: { className?: string }) {
  return (
    <a
      href="#mot-reminder"
      className={`inline-flex items-center gap-1.5 rounded-full border border-emerald-700/60 bg-emerald-900/30 px-3 py-1.5 text-xs font-medium text-emerald-300 transition-colors hover:bg-emerald-900/50 hover:border-emerald-600 ${className}`}
    >
      <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9" />
        <path d="M13.73 21a2 2 0 0 1-3.46 0" />
      </svg>
      Set free MOT reminder &rarr;
    </a>
  );
}

function HeroBulletList({
  bullets,
  className,
}: {
  bullets: string[];
  className: string;
}) {
  return (
    <ul className={`text-sm text-slate-400 ${className}`}>
      {bullets.map((bullet, i) => (
        <li key={i} className="flex items-start gap-2">
          <svg
            className="h-4 w-4 mt-0.5 text-emerald-400 flex-shrink-0"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2.5}
          >
            <path d="M5 13l4 4L19 7" />
          </svg>
          {bullet}
        </li>
      ))}
    </ul>
  );
}
